---
# tasks file for ansible-role-haproxy
- name: install haproxy package
  yum:
    name:
      - haproxy

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes
  when: hostvars[inventory_hostname].ansible_host is defined

- name: copy haproxy conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    backup: yes
    validate: /usr/sbin/haproxy -c -V -f %s
  notify: restart haproxy service

- name: start haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes
