---
# tasks file for ansible-role-haproxy
- name: install haproxy package
  yum:
    name:
      - haproxy

- name: set default listen port
  set_fact:
    haproxy_listen_port: 443
  when: haproxy_ssl_on and haproxy_listen_port == 80

- name: copy haproxy conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify: restart haproxy service

- name: start haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes
