---
# handlers file for ansible-role-haproxy
- name: restart haproxy service
  service:
    name: haproxy
    state: restarted

- name: restart keepalived service
  service:
    name: keepalived
    state: restarted
  when: test_skip is undefined
