---
- name: Converge
  hosts: all
  vars:
    haproxy_backend_servers: ['192.168.0.1:443', '192.168.0.2:443']
    haproxy_cluster: {virtual_ipaddr: '192.168.0.10', check_interface: 'eth0'}
    test_skip: true
  roles:
    - role: ansible-role-haproxy
