---
- name: Converge
  hosts: all
  vars:
    haproxy_backend_servers: ['192.168.0.1:443', '192.168.0.2:443']
    haproxy_cluster_info: {virtual_ipaddr: '192.168.0.10', check_interface: 'eth0'}
    test_skip: true
  pre_tasks:
    - name: create directory
      file:
        path: /etc/haproxy/cert
        state: directory
        mode: '0755'
    - name: create cert files
      shell: 'cd /etc/haproxy/cert; openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -subj /CN=localhost -keyout server.key -out server.crt; cat server.key server.crt > server.pem' # noqa 301 204
      args:
        creates: /etc/haproxy/cert/server.pem
  roles:
    - role: ansible-role-haproxy
